AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Event Processing and Util for ULTRA

Parameters:
  DomainName:
    Type: String
    Description: Domian name for api
  SSMPath:
    Type: String
    Description: Base path in SSM the api will read config from
  SecurityGroup1:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for API (To access rds?)
  SecurityGroup2:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for API (To access rds?)
  Subnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for api (To access rds?)
  Subnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for api (To access rds?)
  RestApiId: 
    Type: AWS::Serverless::Api
    Description: ARN of the serverless api

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs14.x
  Api:
    BinaryMediaTypes:
    - application~1octet-stream

Resources:
  
  SegmentEventQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../event-source/segment/src
      Timeout: 20
      Handler: query.query_handler
      Events:
        SegmentEventQueryRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiId
            Method: GET
            Path: /stream/segment/query{streamid}
      Environment:
        Variables:
          SSMPath: !Ref SSMPath
      VpcConfig:
        SecurityGroupIds:
            - !Ref SecurityGroup1
            - !Ref SecurityGroup2
        SubnetIds:
            - !Ref Subnet1
            - !Ref Subnet2
      Policies:
      - Statement:
        - Effect: Allow
          Action:
            - 'ssm:GetParametersByPath'
            - 'ssm:GetParameter'
          Resource:
            - !Sub 'arn:aws:ssm:us-east-1:${AWS::AccountId}:parameter${SSMPath}' 
            - !Sub 'arn:aws:ssm:us-east-1:${AWS::AccountId}:parameter${SSMPath}*' 
          Sid: PropertiesAccess
  