AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Multi level base path mapping

Parameters:
  DomainName:
    Type: String
    Description: Domian name for api
  ZoneId:
    Type: String
    Description: Zone ID 
    Default: none
  CertArn:
    Type: String
    Description: Certificate ARN
    Default: none
  SSMPath:
    Type: String
    Description: Base path in SSM the api will read config from
  PoolID:
    Type: String
    Description: Id (NOT THE ARN) of the user pool
    

Resources:
  CustomDomainName: # Creates the domain name
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations: 
        - EndpointType: REGIONAL
          CertificateArn: !Ref CertArn

  DomainRecordSet: # Creates a record set in the hosted zone for the domain
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName
      HostedZoneId: !Ref ZoneId
      AliasTarget: 
        DNSName: !GetAtt CustomDomainName.RegionalDomainName
        HostedZoneId: !GetAtt CustomDomainName.RegionalHostedZoneId
      Type: A




  APIMapping: # Creates the mapping for Reporting V1
    Type: AWS::ApiGatewayV2::ApiMapping
    DependsOn: API
    Properties: 
      ApiId: !Ref API
      ApiMappingKey: "api"
      DomainName: !Ref DomainName
      Stage: !Ref API.Stage

  API: # endpoint
    Type: AWS::Serverless::Api
    Properties:
      Description: !Sub "Unified API for ${DomainName}"
      Name: !Sub "Unified API for ${DomainName}"
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
        x-amazon-apigateway-importexport-version: "1.0"

  TransmitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../Backend/Transmit
      Timeout: 20
      Runtime: nodejs14.x
      Handler: index.transmit_handler
      Events:
        SegmentEventQueryRequest:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /transmit
            Method: Post
      Policies:
      - Statement:
        - Effect: Allow
          Action:
            - 's3:*'
          Resource:
            - '*' 
          Sid: PropertiesAccess

  QueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../Backend/Query
      Timeout: 20
      Runtime: nodejs14.x
      Handler: index.query_handler
      Events:
        SegmentEventQueryRequest:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /get/{id}
            Method: Get
      Policies:
      - Statement:
        - Effect: Allow
          Action:
            - 's3:*'
          Resource:
            - '*'
          Sid: PropertiesAccess

  StaticHostingApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./frontend.yaml
      Parameters:
        DomainName: !Ref CustomDomainName

